app/modules/user/models.py
from app.db import db
from werkzeug import generate_password_hash
from libs.tools import code_generator


class User(db.Document):
    name = db.StringField(required=True)
    state = db.StringField(required=True)
    code = db.StringField(required=True)
    active = db.BooleanField(required=True, default=True)
    password = db.StringField()
    email = db.StringField(required=True)
    rol = db.StringField(required=True)
    protected = db.BooleanField(required=True, default=False)
    deleted = db.BooleanField(required=True, default=False)

    def generate_password(self):
        """Calculate the password."""
        self.password = generate_password_hash(self.password)

    def generate_code(self):
        """Calculate the password."""
        self.code = code_generator(size=30, hexdigits=True)

    def is_active(self):
        """True, as all users are active."""
        return True

    def get_id(self):
        """Return the email address to satisfy Flask-Login's requirements."""
        return self.id.__str__()

    def is_authenticated(self):
        """Return True if the user is authenticated."""
        return self.authenticated

    def is_anonymous(self):
        """False, as anonymous users aren't supported."""
        return False

app/modules/user/forms.py
# -*- coding: utf-8 -*-
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm as Form
# , RecaptchaField
from app.libs.validators import UniqueValidator
from models import User
# Import Form elements such as TextField and BooleanField (optional)
from wtforms import (
    TextField,
    PasswordField,
    SelectField,
    ValidationError,
    HiddenField,
    BooleanField
)

# Import Form validators
from wtforms.validators import(
    Required,
    Email,
    Length,
    DataRequired,
    EqualTo
)


# Define the login form (WTForms)

# def password_check(form, field):
#     print field.data
#     size = len(field.data)
#     if size > 6 and size > 8:
#         raise ValidationError(u'La contraseña debe \
#          tener entre 6 y 8 carácteres')
#     if field.data != form.confirm.data:
#         raise ValidationError(u'Las contraseñas deben coincidir')

rol_choices = [('admin', 'Administrador'),
               ('editor', 'Editor'),
               ('viewer', 'Lectura')]
state_choices = [('confirm', 'Confirmar Correo'),
                 ('confirmed', 'Correo Confirmado'),
                 ('reset', u'Cambio de Contraseña'),
                 ('email_reset', u'Cambio de Correo')]


class UserForm(Form):
    email = TextField(u'Correo Electrónico', [
        Email(message=u"El Correo Electronico no es Válido"),
        Required(message=u'Debe ingresar un correo electrónico'),
        UniqueValidator(User,
                        'email',
                        u'El Correo ya se utilizó para otra cuenta')])
    name = TextField('Nombre',
                     [Length(max=25),
                      Required(message='Debe ingresar un Nombre')])
    active = BooleanField('Activo')
    rol = SelectField('Rol',
                      [Required(message='Debe seleccionar el Rol')],
                      choices=rol_choices,
                      coerce=unicode,
                      default='viewer')


class PasswordForm(Form):
    password = PasswordField(u'Nueva Contraseña', [
        Length(max=8,
               min=6,
               message=u'La contraseña debe tener entre 6 y 8 carácteres'),
        DataRequired(message=u'Debe ingresar una contraseña válida'),
        EqualTo('confirm', message=u'Las contraseñas deben coincidir')],
        render_kw={"placeholder": u"Ingrese Nueva Password"})
    confirm = PasswordField(u'Repita Contraseña',
      render_kw={"placeholder": u"Confirme Nueva Password"})
    id = HiddenField('id')
    code = HiddenField('code')


class EditUserForm(Form):
    email = TextField(u'Correo Electrónico', [
        Email(message=u"El Correo Electronico no es Válido"),
        Required(message=u'Debe ingresar un correo electrónico'),
        UniqueValidator(User,
                        'email',
                        u'El Correo ya se utilizó para otra cuenta')])
    name = TextField('Nombre',
                     [Length(max=25),
                      Required(message='Debe ingresar un Nombre')])
    active = BooleanField('Activo')
    rol = SelectField('Rol',
                      [Required(message='Debe seleccionar el Rol')],
                      choices=rol_choices,
                      coerce=unicode)
    password = PasswordField(u'Nueva Contraseña')
    confirm = PasswordField(u'Repita Contraseña')
    id = HiddenField('id')

    def validate_password(form, field):
        size = len(field.data)
        if size > 0:
            if size < 6 or size > 8:
                raise ValidationError(u'La contraseña debe \
                 tener entre 6 y 8 carácteres')
        if field.data != form.confirm.data:
            raise ValidationError(u'Las contraseñas deben coincidir')


class LoginForm(Form):
    email = TextField(u'Correo Electrónico', [
        Email(message=u"El Correo Electronico no es Válido"),
        Required(message=u'Debe ingresar un correo electrónico')],
        render_kw={"placeholder": u"Ingrese su Email"})
    password = PasswordField(u'Contraseña', [
        DataRequired(message=u'Debe ingresar una contraseña válida')],
        render_kw={"placeholder": u"Contraseña"})

app/modules/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)
config = {}
config['name'] = "Usuarios"
config['menu'] = {'list': {'link': 'user.list', 'name': 'Lista'},
                  'create': {'link': 'user.create', 'name': 'Crear'}}

from controllers import *


def get_config():
	return config

app/modules/user/controllers.py
# -*- coding: utf-8 -*-
# Import flask dependencies
from flask import (
    Blueprint,
    request,
    render_template,
    flash,
    g,
    redirect,
    url_for,
    jsonify
)
from flask_login import login_required

import re
# Import the database object from the main app module
import json

from forms import (
    UserForm,
    EditUserForm,
    PasswordForm,
    rol_choices,
    state_choices
)
from libs.tools import sendmail

# Import module models (i.e. User)
from models import User

# Define the blueprint: 'auth', set its url prefix: url/auth
from . import user, config
from app.modules import principal_menu
from app.login import admin, user as view


# Set the route and accepted methods
@user.route('/', methods=['GET'])
@user.route('/list', methods=['GET', 'POST'])
@login_required
@admin.require(http_exception=403)
def list():
    """List Method."""
    if request.method == 'POST':
        data = json.loads(request.form.get("args"))
        draw = data['draw']
        length = data['length']
        start = data['start']
        search = data['search']['value']
        result = []
        response = {}
        count = 0
        total = User.objects.filter(deleted=False).count()
        keys = User._fields.keys()
        keys.remove('password')
        fields = keys[:]
        keys.remove('id')
        keys.remove('protected')
        if search:
            params = [{'deleted': False}]
            regex = re.compile('.*%s.*' % search)
            for key in keys:
                params.append({key: regex})
            try:
                result = User.objects.filter(__raw__={"$or": params}) \
                                     .only(*fields) \
                                     .limit(length) \
                                     .skip(start)
                count = User.objects.filter(__raw__={"$or": params}) \
                                    .count()
            except Exception as e:
                print e
        else:
            try:
                result = User.objects.filter(deleted=False) \
                                     .only(*fields) \
                                     .limit(length) \
                                     .skip(start)
                count = total
            except Exception as e:
                print e

        # order = int(request.form.get('order[0][column]'))
        # order_dir = request.form.get('order[0][dir]')
        response['draw'] = draw
        response["recordsTotal"] = total
        response["recordsFiltered"] = count
        response["data"] = result
        return jsonify(response)
    return render_template("user/list.html",
                           menu=principal_menu(),
                           config=config,
                           rol_choices=dict(rol_choices),
                           state_choices=dict(state_choices))


# Set the route and accepted methods
@user.route('/create', methods=['GET', 'POST'])
@login_required
@admin.require(http_exception=403)
def create():
    """Create Method."""
    form = UserForm(request.form)
    if form.validate_on_submit():
        obj = User()
        form.populate_obj(obj)
        obj.generate_code()
        obj.state = "confirm"
        new_user = User.objects.insert(obj)
        receivers = [{'email': obj.email, 'name': obj.name}]
        code = obj.code
        _id = str(new_user.id)
        url = request.referrer.split(request.path)[0]
        sm = sendmail(receivers, _type=1, code=code, _id=_id, url=url)
        if not sm:
            flash("Error enviando correo de confirmación", "error")
        else:
            flash("Un correo ha sido enviado a %s" % obj.email, "success")
            flash("Confirme el correo para activar cuenta", "info")
        return redirect(url_for("user.list"))
    return render_template("user/create.html",
                           action="create",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@user.route('/edit/<string:key>', methods=['GET', 'POST'])
@login_required
@admin.require(http_exception=403)
def edit(key):
    """Edit Method."""
    try:
        element = User.objects.filter(deleted=False,
                                      id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("user.list"))
    if request.method == 'GET':
        form = EditUserForm(request.form, element)
        return render_template("user/create.html",
                               action="edit",
                               form=form,
                               menu=principal_menu(),
                               config=config)
    form = EditUserForm(request.form)
    if form.validate_on_submit():
        email = element.email
        new_email = form.email.data
        form.populate_obj(element)
        if new_email == email:
            element.save()
            flash("Elemento Actualizado", "success")
            return redirect(url_for("user.list"))
        receivers = [{'email': element.email, 'name': element.name}]
        element.generate_code()
        element.state = "email_reset"
        code = element.code
        _id = str(element.id)
        url = request.referrer.split(request.path)[0]
        sm = sendmail(receivers, _type=1, code=code, _id=_id, url=url)
        if not sm:
            flash("Error enviando correo de confirmación", "error")
        else:
            flash("Un correo ha sido enviado a %s" % new_email, "success")
            flash("Confirme el correo para reactivar cuenta", "info")
        element.save()
        return redirect(url_for("user.list"))
    return render_template("user/create.html",
                           action="edit",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@user.route('/view/<string:key>', methods=['GET'])
@login_required
@admin.require(http_exception=403)
def view(key):
    """View Method."""
    try:
        element = User.objects.filter(deleted=False,
                                      id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("user.list"))
    form = EditUserForm(request.form, element)
    return render_template("user/create.html",
                           action="view",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@user.route('/delete/<string:key>', methods=['GET'])
@login_required
@admin.require(http_exception=403)
def delete(key):
    """Delete Method."""
    try:
        element = User.objects.filter(deleted=False,
                                      id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("user.list"))
    if not element.protected:
        element.update(deleted=True)
        flash("Elemento Eliminado", "success")
    else:
        flash("Elemento Protegido, no se puede eliminar", "info")
    return redirect(url_for("user.list"))


@user.route('/reset_password/<string:key>', methods=['GET'])
@login_required
@admin.require(http_exception=403)
def reset_password(key):
    """Reset Method."""
    try:
        element = User.objects.filter(deleted=False,
                                      id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("user.list"))
    mail = element.email
    ##### Enviar correo para restablecer contraseña
    element.generate_code()
    element.state = "reset"
    element.save()
    flash("Un correo ha sido enviado a %s" % mail, "success")
    return redirect(url_for("user.list"))


@user.route('/<string:key>/activate/<string:token>', methods=['GET', 'POST'])
def activate(key, token):
    """Activate Method."""
    try:
        element = User.objects.filter(deleted=False,
                                      id=key,
                                      code=token).first()
    except Exception:
        flash("Usuario no Existe", "error")
        return redirect(url_for("index"))
    if element.state == 'confirmed':
        flash(u"Contraseña Actualizada Anteriormente", "info")
        return redirect(url_for('auth.login'))
    if element.state == "email_reset":
        element.state = "confirmed"
        element.save()
        flash(u"Correo Actualizado", "success")
        return redirect(url_for('auth.login'))
    form = PasswordForm(request.form, element)
    if request.method == 'GET':
        return render_template("auth/password.html",
                               form=form)
    if form.validate_on_submit():
        state = element.state
        password = form.password.data
        element.password = password
        element.generate_password()
        element.state = "confirmed"
        element.save()
        flash(u"Contraseña Actualizada", "success")
        if state == 'confirm':
            flash(u"Cuenta Activada", "info")
        return redirect(url_for('auth.login'))
    return render_template("auth/password.html",
                           form=form)

app/templates/user/list.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
    <!-- Datatables -->
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

{% endblock %}
{% block content %}
          <div class="right_col" role="main">
            <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lista de Elementos <small>{{config['name']}}</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li>
                        <a class="close-link">
                          <i class="fa fa-close"></i>
                        </a>
                      </li> -->
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                      Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
                    </p>
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Email</th>
                          <th>Rol</th>
                          <th>Estado</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tfoot>
                        <tr>
                          <th>Nombre</th>
                          <th>Email</th>
                          <th>Rol</th>
                          <th>Estado</th>
                          <th>Acciones</th>
                        </tr>
                      </tfoot>
                    </table>

                  </div>
                </div>
              </div>
            </div>
			<form method="post" action="/">
			    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
			</form>
          </div>
{% endblock %}
{% block scripts %}
{{ super() }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Datatables -->
    <script>
      $(document).ready(function() {
        $('#datatable-responsive').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
              'url': "{{url_for('user.list')}}",
              'type': "POST",
              'headers': {'X-CSRFToken': $("input[name=csrf_token]").val()},
              'data': function ( args ) {
                return { "args": JSON.stringify( args ) };
              }
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        var a = {{ rol_choices|tojson }};
                        return a[data] 
                    },
                    "targets": 2
                },
                {
                    "render": function ( data, type, row ) {
                        if(data){
                          var a = {{ state_choices|tojson }};
                          return a[data] 
                        }
                        return "Sin Estado"
                    },
                    "targets": 3
                },
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        html = '<a href="'+'{{url_for("user.view", key="")}}'+row._id.$oid+'" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Ver </a>\
                         <a href="'+'{{url_for("user.edit", key="")}}'+row._id.$oid+'" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Editar </a>\
                         <a href="'+'{{url_for("user.delete", key="")}}'+row._id.$oid+'" class="btn btn-danger btn-xs" onclick="return confirm(`Está seguro que desea borrar este Usuario?`);"><i class="fa fa-trash-o"></i> Eliminar </a>';
                        return html;
                    },
                    "targets": 4,
                    "orderable": false,
                    "width": "20%"
                }
            ],
            "columns": [
              { "data": "name","className":"tr", // can be null or undefined
              "defaultContent": "<i>Not set</i>" },
              { "data": "email","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "rol","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "state","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"}
              ]
        });
      });
    </script>
{% endblock %}
<!-- {% with errors = get_flashed_messages(category_filter=["success"]) %}
{% if errors %}
{% for error in errors %}
{{ error }}<br>
{% endfor %}
{% endif %}
{% endwith %}
lista de elementos de inventario -->