app/modules/inventory/models.py
from app.db import db
import datetime


class Inventory(db.Document):
    optico = db.StringField(required=True)
    tipo = db.StringField(required=True)
    ean = db.StringField(required=True)
    deleted = db.BooleanField()

app/modules/inventory/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm as Form# , RecaptchaField

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import TextField, SelectField, PasswordField # BooleanField

# Import Form validators
from wtforms.validators import Required, Email, EqualTo, Length


# Define the login form (WTForms)
tipo_choices = [('sol', 'Sol'),
                ('opticos', 'Opticos'),
                ('lectura', 'Lectura')]


class InventoryForm(Form):
    optico = TextField('Optico',
                       [Required(message='Debe ingresar nombre del optico')])
    tipo = SelectField('Tipo',
                       [Required(message='Debe seleccionar el tipo')],
                       choices=tipo_choices,
                       coerce=unicode)
    ean = TextField('Codigo de barra',
                    [Length(max=10),
                     Required(message='Debe ingresar el codigo de barra')])

app/modules/inventory/__init__.py
from flask import Blueprint


inventory = Blueprint('inventory', __name__)
config = {}
config['name'] = "Inventario"
config['menu'] = {'list': {'link': 'inventory.list', 'name': 'Lista'},
                  'create': {'link': 'inventory.create', 'name': 'Crear'}}

from controllers import *


def get_config():
    return config

app/modules/inventory/controllers.py
"""Controller of inventory."""
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, \
                  jsonify
from flask_login import login_required

import re
# Import the database object from the main app module
import json

from forms import InventoryForm, tipo_choices

# Import module models (i.e. User)
from models import Inventory

# Define the blueprint: 'auth', set its url prefix: url/auth
from . import inventory, config
# from inventory import principal_menu
from app.modules import principal_menu
from app.login import admin, editor, user as view


@inventory.route('/', methods=['GET'])
@inventory.route('/list', methods=['GET', 'POST'])
@login_required
def list():
    """List Method."""
    if request.method == 'POST':
        data = json.loads(request.form.get("args"))
        draw = data['draw']
        length = data['length']
        start = data['start']
        search = data['search']['value']
        result = []
        response = {}
        count = 0
        total = Inventory.objects.filter(deleted=False).count()
        if search:
            keys = Inventory._fields.keys()
            keys.remove('id')
            params = [{'deleted': False}]
            regex = re.compile('.*%s.*' % search)
            for key in keys:
                params.append({key: regex})
            try:
                result = Inventory.objects.filter(__raw__={"$or": params}) \
                                          .limit(length) \
                                          .skip(start)
                count = Inventory.objects.filter(__raw__={"$or": params}) \
                                         .count()
            except Exception as e:
                print e
        else:
            try:
                result = Inventory.objects.filter(deleted=False) \
                                          .limit(length) \
                                          .skip(start)
                count = total
            except Exception as e:
                print e

        # order = int(request.form.get('order[0][column]'))
        # order_dir = request.form.get('order[0][dir]')
        response['draw'] = draw
        response["recordsTotal"] = total
        response["recordsFiltered"] = count
        response["data"] = result
        return jsonify(response)
    return render_template("inventory/list.html",
                           menu=principal_menu(),
                           config=config,
                           tipo_choices=dict(tipo_choices))


@inventory.route('/create', methods=['GET', 'POST'])
@editor.require(http_exception=403)
@login_required
def create():
    """Create Method."""
    form = InventoryForm(request.form)
    if form.validate_on_submit():
        obj = Inventory()
        form.populate_obj(obj)
        obj.deleted = False
        Inventory.objects.insert(obj)
        flash("Elemento creado", "success")
        return redirect(url_for("inventory.list"))
    return render_template("inventory/create.html",
                           action="create",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@inventory.route('/edit/<string:key>', methods=['GET', 'POST'])
@editor.require(http_exception=403)
@login_required
def edit(key):
    """Edit Method."""
    try:
        element = Inventory.objects.filter(deleted=False,
                                           id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("inventory.list"))
    if request.method == 'GET':
        form = InventoryForm(request.form, element)
        return render_template("inventory/create.html",
                               action="edit",
                               form=form,
                               menu=principal_menu(),
                               config=config)
    else:
        form = InventoryForm(request.form)
        if form.validate_on_submit():
            element.update(**form.data)
            flash("Elemento Actualizado", "success")
            return redirect(url_for("inventory.list"))
        return render_template("inventory/create.html",
                               action="edit",
                               form=form,
                               menu=principal_menu(),
                               config=config)


@inventory.route('/view/<string:key>', methods=['GET'])
@login_required
def view(key):
    """Edit Method."""
    try:
        element = Inventory.objects.filter(deleted=False,
                                           id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("inventory.list"))
    form = InventoryForm(request.form, element)
    return render_template("inventory/create.html",
                           action="view",
                           form=form,
                           menu=principal_menu(),
                           config=config)


@inventory.route('/delete/<string:key>', methods=['GET'])
@editor.require(http_exception=403)
@login_required
def delete(key):
    """Delete Method."""
    try:
        element = Inventory.objects.filter(deleted=False,
                                           id=key).first()
    except Exception:
        flash("Elemento No encontrado", "error")
        return redirect(url_for("inventory.list"))
    element.update(deleted=True)
    flash("Elemento Eliminado", "success")
    return redirect(url_for("inventory.list"))


@inventory.route('/export/<string:type>', methods=['GET'])
@inventory.route('/export/<string:type>/<string:key>', methods=['GET'])
@login_required
def export(type='xls', key=None):
    """Export Method."""
    pass

app/templates/inventory/create.html
{% extends "layout.html" %}
{% block content %}
        <div class="right_col" role="main">
          <div class="">
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                  {% if request.endpoint == "inventory.edit" %}
                    <h2>Editar Elemento<small>{{config['name']}}</small></h2>
                    {% else %}
                    <h2>Crear Elemento<small>{{config['name']}}</small></h2>
                  {% endif %}
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li> -->
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    {% if action == 'view' %}
                    <form class="form-horizontal form-label-left">
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.optico.name}}">{{form.optico.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        {{form.optico(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.tipo.name}}">{{form.tipo.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                        {{form.tipo(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.ean.name}}">{{form.ean.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          {{form.ean(class="form-control col-md-7 col-xs-12", disabled=True)}}
                        </div>
                      </div>                 
                    </form>
                    {% else %}
                    <form id="demo-form2" data-parsley-validate method="POST" action="{{ request.path }}" class="form-horizontal form-label-left">
					           {{ form.hidden_tag() }}
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.optico.name}}">{{form.optico.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                     	{% if form.optico.errors %}
                     		{{form.optico(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                     	{% else %}
                     		{{form.optico(class="form-control col-md-7 col-xs-12")}}
                     	{% endif %}
                        </div>
        			            {% if form.optico.errors %}
        			        	<ul class="errors text-danger">
        			            {% for error in form.optico.errors %}
        			            	<li>{{ error }}</li>
        			            {% endfor %}
        			        	</ul>
        			        	{% endif %}
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.tipo.name}}">{{form.tipo.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                     	{% if form.tipo.errors %}
                     		{{form.tipo(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                     	{% else %}
                     		{{form.tipo(class="form-control col-md-7 col-xs-12")}}
                     	{% endif %}
                        </div>
                        {% if form.tipo.errors %}
        			        	<ul class="errors text-danger">
        			            {% for error in form.tipo.errors %}
        			            	<li>{{ error }}</li>
        			            {% endfor %}
        			        	</ul>
        			        	{% endif %}
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="{{form.ean.name}}">{{form.ean.label}}
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                       	{% if form.ean.errors %}
                       		{{form.ean(class="form-control col-md-7 col-xs-12", style="border:1px solid #a94442")}}
                       	{% else %}
                       		{{form.ean(class="form-control col-md-7 col-xs-12")}}
                       	{% endif %}
                        </div>
                        {% if form.ean.errors %}
        			        	<ul class="errors text-danger">
        			            {% for error in form.ean.errors %}
        			            	<li>{{ error }}</li>
        			            {% endfor %}
        			        	</ul>
        			        	{% endif %}
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                          <a href="{{url_for("inventory.list")}}" class="btn btn-primary">Cancelar</a>
                          <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                      </div>
                    </form>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}


<!-- {% with errors = get_flashed_messages(category_filter=["success"]) %}
{% if errors %}
{% for error in errors %}
{{ error }}<br>
{% endfor %}
{% endif %}
{% endwith %}
lista de elementos de inventario -->

app/templates/inventory/list.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
    <!-- Datatables -->
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

{% endblock %}
{% block content %}
          <div class="right_col" role="main">
            <div class="">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Lista de Elementos <small>{{config['name']}}</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li>
                        <a class="close-link">
                          <i class="fa fa-close"></i>
                        </a>
                      </li> -->
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <p class="text-muted font-13 m-b-30">
                      Responsive is an extension for DataTables that resolves that problem by optimising the table's layout for different screen sizes through the dynamic insertion and removal of columns from the table.
                    </p>
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                          <th>Optico</th>
                          <th>Tipo</th>
                          <th>EAN</th>
                          <th>Acciones</th>
                        </tr>
                      </thead>
                      <tfoot>
                        <tr>
                          <th>Optico</th>
                          <th>Tipo</th>
                          <th>EAN</th>
                          <th>Acciones</th>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </div>
              </div>
            </div>
      <form method="post" action="/">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      </form>
          </div>
{% endblock %}
{% block scripts %}
{{ super() }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Datatables -->
    <script>
      $(document).ready(function() {
        $('#datatable-responsive').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
              'url': "{{url_for('inventory.list')}}",
              'type': "POST",
              'headers': {'X-CSRFToken': $("input[name=csrf_token]").val()},
              'data': function ( args ) {
                return { "args": JSON.stringify( args ) };
              }
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        var a = {{ tipo_choices|tojson }};
                        return a[data] 
                    },
                    "targets": 1
                },
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        html = '<a href="'+'{{url_for("inventory.view", key="")}}'+row._id.$oid+'" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Ver </a>\
                         <a href="'+'{{url_for("inventory.edit", key="")}}'+row._id.$oid+'" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Editar </a>\
                         <a href="'+'{{url_for("inventory.delete", key="")}}'+row._id.$oid+'" class="btn btn-danger btn-xs" onclick="return confirm(`Está seguro que desea borrar este Elemento?`);"><i class="fa fa-trash-o"></i> Eliminar </a>';
                        return html;
                    },
                    "targets": 3,
                    "orderable": false,
                    "width": "20%"
                }
            ],
            "columns": [
              { "data": "optico","className":"tr", // can be null or undefined
              "defaultContent": "<i>Not set</i>" },
              { "data": "tipo","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"},
              { "data": "ean","className":"tr" , // can be null or undefined
                  "defaultContent": "<i>Not set</i>"}
              ]
        });
      });
    </script>
{% endblock %}
<!-- {% with errors = get_flashed_messages(category_filter=["success"]) %}
{% if errors %}
{% for error in errors %}
{{ error }}<br>
{% endfor %}
{% endif %}
{% endwith %}
lista de elementos de inventario -->